### PR TITLE
Return link to classifier to version 2020.8

### PR DESCRIPTION
**Pull request by mbarrier**
Return link to classifier file to 2020.8 version. This needs to stay the older version.

### CODE REVIEW

**Comment by cdiener** [comment]
Is that because the installed Qiime version is older than the classifier now? I could also update the used Qiime version to 2021.4...

**Comment by mbarrier** [comment]
Yes. The easy fix is just to return the classifier to the old version. I'm sorry, I overcorrected when I was fixing the links to the Qiime2.org info pages.

**Comment by cdiener** [comment]
No worries, I should update the Qiime version anyways. Let me if that works...

**Comment by mbarrier** [comment]
It's now erroring on the qiime2 install 
[22:59:32] 🐍 Downloading miniconda...                                     setup_qiime2.py:39
[22:59:33] 🐍 Done.                                                        setup_qiime2.py:45
           🐍 Installing miniconda...                                      setup_qiime2.py:39
[23:00:02] 🐍 Installed miniconda to `/usr/local` 🐍                       setup_qiime2.py:45
           🔍 Downloading Qiime 2 package list...                          setup_qiime2.py:39
           🔍 Done.                                                        setup_qiime2.py:45
           🔍 Installing Qiime 2. This may take a little bit.              setup_qiime2.py:39
            🕐                                                                               
[23:00:03] could not install Qiime 2 😭                                    setup_qiime2.py:47
           SpecNotFound: Invalid name, try the format: user/package                          
                                                                                             
                                                                                             
           Cleaned up unneeded files.                                      setup_qiime2.py:34
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

**Comment by mbarrier** [comment]
Some colleagues want to use your lesson tomorrow for some students to try, so it would be good if you could revert it back to the older version for now to be sure it's up and running fine. 
I haven't worked with Colaboratory before, so I'm using this as an example project for me to learn. I can try out updating everything on my fork to see if I can get it all up and working there, so it won't break your original. :)

**Comment by mbarrier** [comment]
That did it! It's all working now. Thanks for getting that updated.

**Comment by cdiener** [comment]
Yep, should work now.

**Pull request closed without merging**
